openapi: 3.0.0
info:
  version: '0.1'
  title: 'LBAW FinJet Web API'
  description: 'Recursos web (A7) para FinJet'
servers:
- url: http://lbaw2191.lbaw.fe.up.pt
  description: 'Production Server'
externalDocs:
  url: https://git.fe.up.pt/lbaw/lbaw2122/lbaw2191/-/wikis/home
  description: 'Encontre mais informação na wiki'
tags:
  - name: 'M01: Autenticação e perfil individual'
  - name: 'M02: Administração de utilizadores e páginas estáticas'
  - name: 'M03: Pesquisa de questões'
  - name: 'M04: Visualização, votação e resposta a questões'
  - name: 'M05: Criação e edição de questões. Edição de respostas e comentários'
paths:
  /login:
    put:
      operationId: R101
      summary: 'R101: Formulário de Login'
      description: 'Providencia um formulário de login. Acesso: PUB'
      tags:
      - 'M01: Autenticação e perfil individual'
      responses:
        '200':
          description: 'Ok. Mostra formulário de login'